[project]
name = 'Specialized-Disaster-Resistant-Seed-Storage'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.access-protocol]
path = 'contracts/access-protocol.clar'
clarity_version = 2
epoch = 2.5

[contracts.inventory-management]
path = 'contracts/inventory-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
